<?php function googlefont_select() { $krsgfont_array[] = array('value'=>'Abel','label'=>'Abel '); // 1
		$krsgfont_array[] = array('value'=>'Abril Fatface','label'=>'Abril Fatface');
		$krsgfont_array[] = array('value'=>'Aclonica','label'=>'Aclonica');
		$krsgfont_array[] = array('value'=>'Acme','label'=>'Acme');
		$krsgfont_array[] = array('value'=>'Actor','label'=>'Actor ');
		$krsgfont_array[] = array('value'=>'Adamina','label'=>'Adamina');
		$krsgfont_array[] = array('value'=>'Advent Pro','label'=>'Advent Pro');
		$krsgfont_array[] = array('value'=>'Advent Pro:100,200,300,400,500,600,700','label'=>'Advent Pro (plus all weights)');
		$krsgfont_array[] = array('value'=>'Aguafina Script','label'=>'Aguafina Script');
		$krsgfont_array[] = array('value'=>'Aladin','label'=>'Aladin');
		$krsgfont_array[] = array('value'=>'Aldrich','label'=>'Aldrich ');
		$krsgfont_array[] = array('value'=>'Alex Brush','label'=>'Alex Brush');
		$krsgfont_array[] = array('value'=>'Alfa Slab One','label'=>'Alfa Slab One');
		$krsgfont_array[] = array('value'=>'Alice','label'=>'Alice ');
		$krsgfont_array[] = array('value'=>'Alike Angular','label'=>'Alike Angular');
		$krsgfont_array[] = array('value'=>'Alike','label'=>'Alike ');
		$krsgfont_array[] = array('value'=>'Allan','label'=>'Allan');
		$krsgfont_array[] = array('value'=>'Allerta Stencil','label'=>'Allerta Stencil');
		$krsgfont_array[] = array('value'=>'Allerta','label'=>'Allerta');
		$krsgfont_array[] = array('value'=>'Allura','label'=>'Allura'); //20
		$krsgfont_array[] = array('value'=>'Almendra SC','label'=>'Almendra SC');
		$krsgfont_array[] = array('value'=>'Almendra','label'=>'Almendra');
		$krsgfont_array[] = array('value'=>'Almendra:400,bold','label'=>'Almendra:400,bold');
		$krsgfont_array[] = array('value'=>'Amaranth','label'=>'Amaranth');
		$krsgfont_array[] = array('value'=>'Amarante','label'=>'Amarante');
		$krsgfont_array[] = array('value'=>'Amatic SC','label'=>'Amatic SC');
		$krsgfont_array[] = array('value'=>'Amatic SC:400,700','label'=>'Amatic SC:400,700');
		$krsgfont_array[] = array('value'=>'Amethysta','label'=>'Amethysta');
		$krsgfont_array[] = array('value'=>'Andada','label'=>'Andada');
		$krsgfont_array[] = array('value'=>'Andika','label'=>'Andika ');
		$krsgfont_array[] = array('value'=>'Annie Use Your Telescope','label'=>'Annie Use Your Telescope');
		$krsgfont_array[] = array('value'=>'Anonymous Pro','label'=>'Anonymous Pro');
		$krsgfont_array[] = array('value'=>'Anonymous Pro:regular,italic,bold,bolditalic','label'=>'Anonymous Pro (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Antic Didone','label'=>'Antic Didone');
		$krsgfont_array[] = array('value'=>'Antic Slab','label'=>'Antic Slab');
		$krsgfont_array[] = array('value'=>'Antic','label'=>'Antic');
		$krsgfont_array[] = array('value'=>'Anton','label'=>'Anton');
		$krsgfont_array[] = array('value'=>'Arapey','label'=>'Arapey');
		$krsgfont_array[] = array('value'=>'Arapey:400,400italic','label'=>'Arapey:400,400italic');
		$krsgfont_array[] = array('value'=>'Arbutus','label'=>'Arbutus');
		$krsgfont_array[] = array('value'=>'Architects Daughter','label'=>'Architects Daughter');
		$krsgfont_array[] = array('value'=>'Arimo','label'=>'Arimo');
		$krsgfont_array[] = array('value'=>'Arimo:regular,italic,bold,bolditalic','label'=>'Arimo (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Arizonia','label'=>'Arizonia');
		$krsgfont_array[] = array('value'=>'Armata','label'=>'Armata');
		$krsgfont_array[] = array('value'=>'Artifika','label'=>'Artifika');
		$krsgfont_array[] = array('value'=>'Arvo','label'=>'Arvo');
		$krsgfont_array[] = array('value'=>'Arvo:regular,italic,bold,bolditalic','label'=>'Arvo (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Asap','label'=>'Asap');
		$krsgfont_array[] = array('value'=>'Asap:400,400italic,700,700italic','label'=>'Asap (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Asset','label'=>'Asset');
		$krsgfont_array[] = array('value'=>'Astloch','label'=>'Astloch');
		$krsgfont_array[] = array('value'=>'Astloch:regular,bold','label'=>'Astloch (plus bold)');
		$krsgfont_array[] = array('value'=>'Asul','label'=>'Asul');
		$krsgfont_array[] = array('value'=>'Asul:400,bold','label'=>'Asul:400,bold');
		$krsgfont_array[] = array('value'=>'Atomic Age','label'=>'Atomic Age');
		$krsgfont_array[] = array('value'=>'Aubrey','label'=>'Aubrey ');
		$krsgfont_array[] = array('value'=>'Audiowide','label'=>'Audiowide');
		$krsgfont_array[] = array('value'=>'Average','label'=>'Average');
		$krsgfont_array[] = array('value'=>'Averia Gruesa Libre','label'=>'Averia Gruesa Libre');
		$krsgfont_array[] = array('value'=>'Averia Libre','label'=>'Averia Libre');
		$krsgfont_array[] = array('value'=>'Averia Libre:300,300italic,400,400italic,700,700italic','label'=>'Averia Libre (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Averia Sans Libre','label'=>'Averia Sans Libre');
		$krsgfont_array[] = array('value'=>'Averia Sans Libre:300,300italic,400,400italic,700,700italic','label'=>'Averia Sans Libre (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Averia Serif Libre','label'=>'Averia Serif Libre'); 
		$krsgfont_array[] = array('value'=>'Averia Serif Libre:300,300italic,400,400italic,700,700italic','label'=>'Averia Serif Libre (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Bad Script','label'=>'Bad Script');
		$krsgfont_array[] = array('value'=>'Balthazar','label'=>'Balthazar');
		$krsgfont_array[] = array('value'=>'Bangers','label'=>'Bangers');
		$krsgfont_array[] = array('value'=>'Basic','label'=>'Basic');
		$krsgfont_array[] = array('value'=>'Baumans','label'=>'Baumans');
		$krsgfont_array[] = array('value'=>'Belgrano','label'=>'Belgrano');
		$krsgfont_array[] = array('value'=>'Belleza','label'=>'Belleza');
		$krsgfont_array[] = array('value'=>'Bentham','label'=>'Bentham');
		$krsgfont_array[] = array('value'=>'Berkshire Swash','label'=>'Berkshire Swash');
		$krsgfont_array[] = array('value'=>'Bevan','label'=>'Bevan');
		$krsgfont_array[] = array('value'=>'Bigshot One','label'=>'Bigshot One');
		$krsgfont_array[] = array('value'=>'Bilbo Swash Caps','label'=>'Bilbo Swash Caps');
		$krsgfont_array[] = array('value'=>'Bilbo','label'=>'Bilbo');
		$krsgfont_array[] = array('value'=>'Bitter','label'=>'Bitter');
		$krsgfont_array[] = array('value'=>'Bitter:400,400italic,700','label'=>'Bitter:400,400italic,700');
		$krsgfont_array[] = array('value'=>'Black Ops One','label'=>'Black Ops One ');
		$krsgfont_array[] = array('value'=>'Bonbon','label'=>'Bonbon');
		$krsgfont_array[] = array('value'=>'Boogaloo','label'=>'Boogaloo');
		$krsgfont_array[] = array('value'=>'Bowlby One SC','label'=>'Bowlby One SC');
		$krsgfont_array[] = array('value'=>'Bowlby One','label'=>'Bowlby One');
		$krsgfont_array[] = array('value'=>'Brawler','label'=>'Brawler ');
		$krsgfont_array[] = array('value'=>'Bree Serif','label'=>'Bree Serif');
		$krsgfont_array[] = array('value'=>'Bubblegum Sans','label'=>'Bubblegum Sans');
		$krsgfont_array[] = array('value'=>'Buda:light','label'=>'Buda');
		$krsgfont_array[] = array('value'=>'Buenard','label'=>'Buenard');
		$krsgfont_array[] = array('value'=>'Buenard:400,bold','label'=>'Buenard:400,bold');
		$krsgfont_array[] = array('value'=>'Butcherman','label'=>'Butcherman');
		$krsgfont_array[] = array('value'=>'Butterfly Kids','label'=>'Butterfly Kids');
		$krsgfont_array[] = array('value'=>'Cabin Condensed','label'=>'Cabin Condensed');
		$krsgfont_array[] = array('value'=>'Cabin Condensed:400,500,600,700','label'=>'Cabin Condensed:400,500,600,700');
		$krsgfont_array[] = array('value'=>'Cabin Sketch','label'=>'Cabin Sketch');
		$krsgfont_array[] = array('value'=>'Cabin Sketch:bold','label'=>'Cabin Sketch Bold');
		$krsgfont_array[] = array('value'=>'Cabin Sketch:regular,bold','label'=>'Cabin Sketch:regular,bold');
		$krsgfont_array[] = array('value'=>'Cabin','label'=>'Cabin');
		$krsgfont_array[] = array('value'=>'Cabin:regular,500,600,bold','label'=>'Cabin (plus 500, 600, and bold)');
		$krsgfont_array[] = array('value'=>'Caesar Dressing','label'=>'Caesar Dressing');
		$krsgfont_array[] = array('value'=>'Cagliostro','label'=>'Cagliostro');
		$krsgfont_array[] = array('value'=>'Calligraffitti','label'=>'Calligraffitti');
		$krsgfont_array[] = array('value'=>'Cambo','label'=>'Cambo');
		$krsgfont_array[] = array('value'=>'Candal','label'=>'Candal');
		$krsgfont_array[] = array('value'=>'Cantarell','label'=>'Cantarell');
		$krsgfont_array[] = array('value'=>'Cantarell:regular,italic,bold,bolditalic','label'=>'Cantarell (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Cantata One','label'=>'Cantata One');
		$krsgfont_array[] = array('value'=>'Capriola','label'=>'Capriola');
		$krsgfont_array[] = array('value'=>'Cardo','label'=>'Cardo');
		$krsgfont_array[] = array('value'=>'Carme','label'=>'Carme ');
		$krsgfont_array[] = array('value'=>'Carter One','label'=>'Carter One');
		$krsgfont_array[] = array('value'=>'Caudex','label'=>'Caudex');
		$krsgfont_array[] = array('value'=>'Caudex:regular,italic,bold,bolditalic','label'=>'Caudex (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Cedarville Cursive','label'=>'Cedarville Cursive');
		$krsgfont_array[] = array('value'=>'Ceviche One','label'=>'Ceviche One');
		$krsgfont_array[] = array('value'=>'Changa One','label'=>'Changa One');
		$krsgfont_array[] = array('value'=>'Chango','label'=>'Chango');
		$krsgfont_array[] = array('value'=>'Chau Philomene One','label'=>'Chau Philomene One');
		$krsgfont_array[] = array('value'=>'Chau Philomene One:400,400italic','label'=>'Chau Philomene One (plus italic)');
		$krsgfont_array[] = array('value'=>'Chelsea Market','label'=>'Chelsea Market');
		$krsgfont_array[] = array('value'=>'Cherry Cream Soda','label'=>'Cherry Cream Soda');
		$krsgfont_array[] = array('value'=>'Chewy','label'=>'Chewy');
		$krsgfont_array[] = array('value'=>'Chicle','label'=>'Chicle');
		$krsgfont_array[] = array('value'=>'Chivo','label'=>'Chivo');
		$krsgfont_array[] = array('value'=>'Chivo:400,900','label'=>'Chivo (plus bold)');
		$krsgfont_array[] = array('value'=>'Coda','label'=>'Coda');
		$krsgfont_array[] = array('value'=>'Coda:400,800','label'=>'Coda:400,800');
		$krsgfont_array[] = array('value'=>'Codystar','label'=>'Codystar');
		$krsgfont_array[] = array('value'=>'Codystar:300,400','label'=>'Codystar (plus all weights)');
		$krsgfont_array[] = array('value'=>'Comfortaa','label'=>'Comfortaa ');
		$krsgfont_array[] = array('value'=>'Comfortaa:300,400,700','label'=>'Comfortaa (plus book and bold) ');
		$krsgfont_array[] = array('value'=>'Coming Soon','label'=>'Coming Soon');
		$krsgfont_array[] = array('value'=>'Concert One','label'=>'Concert One');
		$krsgfont_array[] = array('value'=>'Condiment','label'=>'Condiment');
		$krsgfont_array[] = array('value'=>'Contrail One','label'=>'Contrail One');
		$krsgfont_array[] = array('value'=>'Convergence','label'=>'Convergence');
		$krsgfont_array[] = array('value'=>'Cookie','label'=>'Cookie');
		$krsgfont_array[] = array('value'=>'Copse','label'=>'Copse');
		$krsgfont_array[] = array('value'=>'Corben','label'=>'Corben');
		$krsgfont_array[] = array('value'=>'Corben:400,bold','label'=>'Corben:400,bold');
		$krsgfont_array[] = array('value'=>'Corben:bold','label'=>'Corben Bold');
		$krsgfont_array[] = array('value'=>'Courgette','label'=>'Courgette');
		$krsgfont_array[] = array('value'=>'Cousine','label'=>'Cousine');
		$krsgfont_array[] = array('value'=>'Cousine:regular,italic,bold,bolditalic','label'=>'Cousine (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Coustard','label'=>'Coustard ');
		$krsgfont_array[] = array('value'=>'Coustard:400,900','label'=>'Coustard (plus ultra bold) ');
		$krsgfont_array[] = array('value'=>'Covered By Your Grace','label'=>'Covered By Your Grace');
		$krsgfont_array[] = array('value'=>'Crafty Girls','label'=>'Crafty Girls');
		$krsgfont_array[] = array('value'=>'Creepster','label'=>'Creepster');
		$krsgfont_array[] = array('value'=>'Crete Round','label'=>'Crete Round');
		$krsgfont_array[] = array('value'=>'Crete Round:400,400italic','label'=>'Crete Round:400,400italic');
		$krsgfont_array[] = array('value'=>'Crimson Text','label'=>'Crimson Text');
		$krsgfont_array[] = array('value'=>'Crushed','label'=>'Crushed');
		$krsgfont_array[] = array('value'=>'Cuprum','label'=>'Cuprum');
		$krsgfont_array[] = array('value'=>'Cuprum:400,400italic,700italic,700','label'=>'Cuprum (plus bold and italic)');
		$krsgfont_array[] = array('value'=>'Cutive','label'=>'Cutive');
		$krsgfont_array[] = array('value'=>'Damion','label'=>'Damion');
		$krsgfont_array[] = array('value'=>'Dancing Script','label'=>'Dancing Script');
		$krsgfont_array[] = array('value'=>'Dawning of a New Day','label'=>'Dawning of a New Day');
		$krsgfont_array[] = array('value'=>'Days One','label'=>'Days One ');
		$krsgfont_array[] = array('value'=>'Delius Swash Caps','label'=>'Delius Swash Caps ');
		$krsgfont_array[] = array('value'=>'Delius Unicase','label'=>'Delius Unicase ');
		$krsgfont_array[] = array('value'=>'Delius','label'=>'Delius ');
		$krsgfont_array[] = array('value'=>'Della Respira','label'=>'Della Respira');
		$krsgfont_array[] = array('value'=>'Devonshire','label'=>'Devonshire');
		$krsgfont_array[] = array('value'=>'Didact Gothic','label'=>'Didact Gothic');
		$krsgfont_array[] = array('value'=>'Diplomata SC','label'=>'Diplomata SC');
		$krsgfont_array[] = array('value'=>'Diplomata','label'=>'Diplomata');
		$krsgfont_array[] = array('value'=>'Doppio One','label'=>'Doppio One');
		$krsgfont_array[] = array('value'=>'Dorsa','label'=>'Dorsa');
		$krsgfont_array[] = array('value'=>'Dosis','label'=>'Dosis');
		$krsgfont_array[] = array('value'=>'Dosis:200,300,400,500,600,700,800','label'=>'Dosis (all weights)');
		$krsgfont_array[] = array('value'=>'Dr Sugiyama','label'=>'Dr Sugiyama');
		$krsgfont_array[] = array('value'=>'Droid Sans Mono','label'=>'Droid Sans Mono');
		$krsgfont_array[] = array('value'=>'Droid Sans','label'=>'Droid Sans');
		$krsgfont_array[] = array('value'=>'Droid Sans:regular,bold','label'=>'Droid Sans (plus bold)');
		$krsgfont_array[] = array('value'=>'Droid Serif','label'=>'Droid Serif');
		$krsgfont_array[] = array('value'=>'Droid Serif:regular,italic,bold,bolditalic','label'=>'Droid Serif (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Duru Sans','label'=>'Duru Sans');
		$krsgfont_array[] = array('value'=>'Dynalight','label'=>'Dynalight');
		$krsgfont_array[] = array('value'=>'EB Garamond','label'=>'EB Garamond');
		$krsgfont_array[] = array('value'=>'Eagle Lake','label'=>'Eagle Lake');
		$krsgfont_array[] = array('value'=>'Eater','label'=>'Eater');
		$krsgfont_array[] = array('value'=>'Economica','label'=>'Economica');
		$krsgfont_array[] = array('value'=>'Economica:400,400italic,700,700italic','label'=>'Economica (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Electrolize','label'=>'Electrolize');
		$krsgfont_array[] = array('value'=>'Emblema One','label'=>'Emblema One');
		$krsgfont_array[] = array('value'=>'Emilys Candy','label'=>'Emilys Candy');
		$krsgfont_array[] = array('value'=>'Engagement','label'=>'Engagement');
		$krsgfont_array[] = array('value'=>'Enriqueta','label'=>'Enriqueta');
		$krsgfont_array[] = array('value'=>'Enriqueta:400,700','label'=>'Enriqueta:400,700');
		$krsgfont_array[] = array('value'=>'Erica One','label'=>'Erica One');
		$krsgfont_array[] = array('value'=>'Esteban','label'=>'Esteban');
		$krsgfont_array[] = array('value'=>'Euphoria Script','label'=>'Euphoria Script');
		$krsgfont_array[] = array('value'=>'Ewert','label'=>'Ewert');
		$krsgfont_array[] = array('value'=>'Exo','label'=>'Exo');
		$krsgfont_array[] = array('value'=>'Exo:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic','label'=>'Exo (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Expletus Sans','label'=>'Expletus Sans');
		$krsgfont_array[] = array('value'=>'Expletus Sans:regular,500,600,bold','label'=>'Expletus Sans (plus 500, 600, and bold)');
		$krsgfont_array[] = array('value'=>'Fanwood Text','label'=>'Fanwood Text');
		$krsgfont_array[] = array('value'=>'Fanwood Text:400,400italic','label'=>'Fanwood Text (plus italic)');
		$krsgfont_array[] = array('value'=>'Fascinate Inline','label'=>'Fascinate Inline');
		$krsgfont_array[] = array('value'=>'Fascinate','label'=>'Fascinate');
		$krsgfont_array[] = array('value'=>'Fasthand','label'=>'Fasthand');
		$krsgfont_array[] = array('value'=>'Federant','label'=>'Federant');
		$krsgfont_array[] = array('value'=>'Federo','label'=>'Federo ');
		$krsgfont_array[] = array('value'=>'Felipa','label'=>'Felipa');
		$krsgfont_array[] = array('value'=>'Fjord One','label'=>'Fjord One');
		$krsgfont_array[] = array('value'=>'Flamenco','label'=>'Flamenco');
		$krsgfont_array[] = array('value'=>'Flamenco:300','label'=>'Flamenco:300');
		$krsgfont_array[] = array('value'=>'Flavors','label'=>'Flavors');
		$krsgfont_array[] = array('value'=>'Fondamento','label'=>'Fondamento');
		$krsgfont_array[] = array('value'=>'Fondamento:400,400italic','label'=>'Fondamento:400,400italic');
		$krsgfont_array[] = array('value'=>'Fontdiner Swanky','label'=>'Fontdiner Swanky');
		$krsgfont_array[] = array('value'=>'Forum','label'=>'Forum');
		$krsgfont_array[] = array('value'=>'Francois One','label'=>'Francois One');
		$krsgfont_array[] = array('value'=>'Fredoka One','label'=>'Fredoka One');
		$krsgfont_array[] = array('value'=>'Fresca','label'=>'Fresca');
		$krsgfont_array[] = array('value'=>'Frijole','label'=>'Frijole');
		$krsgfont_array[] = array('value'=>'Fugaz One','label'=>'Fugaz One');
		$krsgfont_array[] = array('value'=>'Galdeano','label'=>'Galdeano');
		$krsgfont_array[] = array('value'=>'Galindo','label'=>'Galindo');
		$krsgfont_array[] = array('value'=>'Gentium Basic','label'=>'Gentium Basic ');
		$krsgfont_array[] = array('value'=>'Gentium Basic:400,700,400italic,700italic','label'=>'Gentium Basic (plus bold and italic) ');
		$krsgfont_array[] = array('value'=>'Gentium Book Basic','label'=>'Gentium Book Basic ');
		$krsgfont_array[] = array('value'=>'Gentium Book Basic:400,400italic,700,700italic','label'=>'Gentium Book Basic (plus bold and italic) ');
		$krsgfont_array[] = array('value'=>'Geo','label'=>'Geo');
		$krsgfont_array[] = array('value'=>'Geostar Fill','label'=>'Geostar Fill ');
		$krsgfont_array[] = array('value'=>'Geostar','label'=>'Geostar ');
		$krsgfont_array[] = array('value'=>'Germania One','label'=>'Germania One');
		$krsgfont_array[] = array('value'=>'Give You Glory','label'=>'Give You Glory');
		$krsgfont_array[] = array('value'=>'Glass Antiqua','label'=>'Glass Antiqua');
		$krsgfont_array[] = array('value'=>'Glegoo','label'=>'Glegoo');
		$krsgfont_array[] = array('value'=>'Gloria Hallelujah','label'=>'Gloria Hallelujah ');
		$krsgfont_array[] = array('value'=>'Goblin One','label'=>'Goblin One');
		$krsgfont_array[] = array('value'=>'Gochi Hand','label'=>'Gochi Hand');
		$krsgfont_array[] = array('value'=>'Gochi Hand:400','label'=>'Gochi Hand:400');
		$krsgfont_array[] = array('value'=>'Gorditas','label'=>'Gorditas');
		$krsgfont_array[] = array('value'=>'Gorditas:400,bold','label'=>'Gorditas (plus bold)');
		$krsgfont_array[] = array('value'=>'Goudy Bookletter 1911','label'=>'Goudy Bookletter 1911');
		$krsgfont_array[] = array('value'=>'Graduate','label'=>'Graduate');
		$krsgfont_array[] = array('value'=>'Gravitas One','label'=>'Gravitas One');
		$krsgfont_array[] = array('value'=>'Great Vibes','label'=>'Great Vibes');
		$krsgfont_array[] = array('value'=>'Gruppo','label'=>'Gruppo');
		$krsgfont_array[] = array('value'=>'Gudea','label'=>'Gudea');
		$krsgfont_array[] = array('value'=>'Gudea:400,italic,bold','label'=>'Gudea:400,italic,bold');
		$krsgfont_array[] = array('value'=>'Habibi','label'=>'Habibi');
		$krsgfont_array[] = array('value'=>'Hammersmith One','label'=>'Hammersmith One');
		$krsgfont_array[] = array('value'=>'Handlee','label'=>'Handlee');
		$krsgfont_array[] = array('value'=>'Happy Monkey','label'=>'Happy Monkey');
		$krsgfont_array[] = array('value'=>'Henny Penny','label'=>'Henny Penny');
		$krsgfont_array[] = array('value'=>'Herr Von Muellerhoff','label'=>'Herr Von Muellerhoff');
		$krsgfont_array[] = array('value'=>'Holtwood One SC','label'=>'Holtwood One SC');
		$krsgfont_array[] = array('value'=>'Homemade Apple','label'=>'Homemade Apple');
		$krsgfont_array[] = array('value'=>'Homenaje','label'=>'Homenaje');
		$krsgfont_array[] = array('value'=>'IM Fell DW Pica SC','label'=>'IM Fell DW Pica SC');
		$krsgfont_array[] = array('value'=>'IM Fell DW Pica','label'=>'IM Fell DW Pica');
		$krsgfont_array[] = array('value'=>'IM Fell DW Pica:regular,italic','label'=>'IM Fell DW Pica (plus italic)');
		$krsgfont_array[] = array('value'=>'IM Fell Double Pica SC','label'=>'IM Fell Double Pica SC');
		$krsgfont_array[] = array('value'=>'IM Fell Double Pica','label'=>'IM Fell Double Pica');
		$krsgfont_array[] = array('value'=>'IM Fell Double Pica:regular,italic','label'=>'IM Fell Double Pica (plus italic)');
		$krsgfont_array[] = array('value'=>'IM Fell English SC','label'=>'IM Fell English SC');
		$krsgfont_array[] = array('value'=>'IM Fell English','label'=>'IM Fell English');
		$krsgfont_array[] = array('value'=>'IM Fell English:regular,italic','label'=>'IM Fell English (plus italic)');
		$krsgfont_array[] = array('value'=>'IM Fell French Canon SC','label'=>'IM Fell French Canon SC');
		$krsgfont_array[] = array('value'=>'IM Fell French Canon','label'=>'IM Fell French Canon');
		$krsgfont_array[] = array('value'=>'IM Fell French Canon:regular,italic','label'=>'IM Fell French Canon (plus italic)');
		$krsgfont_array[] = array('value'=>'IM Fell Great Primer SC','label'=>'IM Fell Great Primer SC');
		$krsgfont_array[] = array('value'=>'IM Fell Great Primer','label'=>'IM Fell Great Primer');
		$krsgfont_array[] = array('value'=>'IM Fell Great Primer:regular,italic','label'=>'IM Fell Great Primer (plus italic)');
		$krsgfont_array[] = array('value'=>'Iceberg','label'=>'Iceberg');
		$krsgfont_array[] = array('value'=>'Iceland','label'=>'Iceland');
		$krsgfont_array[] = array('value'=>'Imprima','label'=>'Imprima');
		$krsgfont_array[] = array('value'=>'Inconsolata','label'=>'Inconsolata');
		$krsgfont_array[] = array('value'=>'Inder','label'=>'Inder');
		$krsgfont_array[] = array('value'=>'Indie Flower','label'=>'Indie Flower');
		$krsgfont_array[] = array('value'=>'Inika','label'=>'Inika');
		$krsgfont_array[] = array('value'=>'Inika:400,bold','label'=>'Inika (plus bold)');
		$krsgfont_array[] = array('value'=>'Irish Grover','label'=>'Irish Grover');
		$krsgfont_array[] = array('value'=>'Irish Growler','label'=>'Irish Growler');
		$krsgfont_array[] = array('value'=>'Istok Web','label'=>'Istok Web');
		$krsgfont_array[] = array('value'=>'Istok Web:400,700,400italic,700italic','label'=>'Istok Web (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Italiana','label'=>'Italiana');
		$krsgfont_array[] = array('value'=>'Italianno','label'=>'Italianno');
		$krsgfont_array[] = array('value'=>'Jim Nightshade','label'=>'Jim Nightshade');
		$krsgfont_array[] = array('value'=>'Jockey One','label'=>'Jockey One');
		$krsgfont_array[] = array('value'=>'Jolly Lodger','label'=>'Jolly Lodger');
		$krsgfont_array[] = array('value'=>'Josefin Sans','label'=>'Josefin Sans Regular 400');
		$krsgfont_array[] = array('value'=>'Josefin Sans:100','label'=>'Josefin Sans 100');
		$krsgfont_array[] = array('value'=>'Josefin Sans:100,100italic','label'=>'Josefin Sans 100 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Sans:600','label'=>'Josefin Sans 600');
		$krsgfont_array[] = array('value'=>'Josefin Sans:600,600italic','label'=>'Josefin Sans 600 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Sans:bold','label'=>'Josefin Sans Bold 700');
		$krsgfont_array[] = array('value'=>'Josefin Sans:bold,bolditalic','label'=>'Josefin Sans Bold 700 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Sans:light','label'=>'Josefin Sans Light 300');
		$krsgfont_array[] = array('value'=>'Josefin Sans:light,lightitalic','label'=>'Josefin Sans Light 300 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Sans:regular,regularitalic','label'=>'Josefin Sans Regular 400 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Slab','label'=>'Josefin Slab Regular 400');
		$krsgfont_array[] = array('value'=>'Josefin Slab:100','label'=>'Josefin Slab 100');
		$krsgfont_array[] = array('value'=>'Josefin Slab:100,100italic','label'=>'Josefin Slab 100 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Slab:600','label'=>'Josefin Slab 600');
		$krsgfont_array[] = array('value'=>'Josefin Slab:600,600italic','label'=>'Josefin Slab 600 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Slab:bold','label'=>'Josefin Slab Bold 700');
		$krsgfont_array[] = array('value'=>'Josefin Slab:bold,bolditalic','label'=>'Josefin Slab Bold 700 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Slab:light','label'=>'Josefin Slab Light 300');
		$krsgfont_array[] = array('value'=>'Josefin Slab:light,lightitalic','label'=>'Josefin Slab Light 300 (plus italic)');
		$krsgfont_array[] = array('value'=>'Josefin Slab:regular,regularitalic','label'=>'Josefin Slab Regular 400 (plus italic)');
		$krsgfont_array[] = array('value'=>'Judson','label'=>'Judson');
		$krsgfont_array[] = array('value'=>'Judson:regular,regularitalic,bold','label'=>'Judson (plus bold)');
		$krsgfont_array[] = array('value'=>'Julee','label'=>'Julee');
		$krsgfont_array[] = array('value'=>'Junge','label'=>'Junge');
		$krsgfont_array[] = array('value'=>'Jura','label'=>' Jura Regular');
		$krsgfont_array[] = array('value'=>'Jura:500','label'=>' Jura 500');
		$krsgfont_array[] = array('value'=>'Jura:600','label'=>' Jura 600');
		$krsgfont_array[] = array('value'=>'Jura:light','label'=>' Jura Light');
		$krsgfont_array[] = array('value'=>'Just Another Hand','label'=>'Just Another Hand');
		$krsgfont_array[] = array('value'=>'Just Me Again Down Here','label'=>'Just Me Again Down Here');
		$krsgfont_array[] = array('value'=>'Kameron','label'=>'Kameron');
		$krsgfont_array[] = array('value'=>'Kameron:400,700','label'=>'Kameron (plus bold)');
		$krsgfont_array[] = array('value'=>'Karla','label'=>'Karla');
		$krsgfont_array[] = array('value'=>'Karla:400,400italic,700,700italic','label'=>'Karla (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Kaushan Script','label'=>'Kaushan Script');
		$krsgfont_array[] = array('value'=>'Kelly Slab','label'=>'Kelly Slab ');
		$krsgfont_array[] = array('value'=>'Kenia','label'=>'Kenia');
		$krsgfont_array[] = array('value'=>'Knewave','label'=>'Knewave');
		$krsgfont_array[] = array('value'=>'Kotta One','label'=>'Kotta One');
		$krsgfont_array[] = array('value'=>'Kranky','label'=>'Kranky');
		$krsgfont_array[] = array('value'=>'Kreon','label'=>'Kreon');
		$krsgfont_array[] = array('value'=>'Kreon:light,regular,bold','label'=>'Kreon (plus light and bold)');
		$krsgfont_array[] = array('value'=>'Kristi','label'=>'Kristi');
		$krsgfont_array[] = array('value'=>'Krona One','label'=>'Krona One');
		$krsgfont_array[] = array('value'=>'La Belle Aurore','label'=>'La Belle Aurore');
		$krsgfont_array[] = array('value'=>'Lancelot','label'=>'Lancelot');
		$krsgfont_array[] = array('value'=>'Lato:100','label'=>'Lato 100');
		$krsgfont_array[] = array('value'=>'Lato:100,100italic','label'=>'Lato 100 (plus italic)');
		$krsgfont_array[] = array('value'=>'Lato:900','label'=>'Lato 900');
		$krsgfont_array[] = array('value'=>'Lato:900,900italic','label'=>'Lato 900 (plus italic)');
		$krsgfont_array[] = array('value'=>'Lato:bold','label'=>'Lato Bold 700');
		$krsgfont_array[] = array('value'=>'Lato:bold,bolditalic','label'=>'Lato Bold 700 (plus italic)');
		$krsgfont_array[] = array('value'=>'Lato:light','label'=>'Lato Light 300');
		$krsgfont_array[] = array('value'=>'Lato:light,lightitalic','label'=>'Lato Light 300 (plus italic)');
		$krsgfont_array[] = array('value'=>'Lato:regular','label'=>'Lato Regular 400');
		$krsgfont_array[] = array('value'=>'Lato:regular,regularitalic','label'=>'Lato Regular 400 (plus italic)');
		$krsgfont_array[] = array('value'=>'League Script','label'=>'League Script');
		$krsgfont_array[] = array('value'=>'Leckerli One','label'=>'Leckerli One ');
		$krsgfont_array[] = array('value'=>'Ledger','label'=>'Ledger');
		$krsgfont_array[] = array('value'=>'Lekton','label'=>' Lekton ');
		$krsgfont_array[] = array('value'=>'Lekton:regular,italic,bold','label'=>'Lekton (plus italic and bold)');
		$krsgfont_array[] = array('value'=>'Lemon','label'=>'Lemon');
		$krsgfont_array[] = array('value'=>'Life Savers','label'=>'Life Savers');
		$krsgfont_array[] = array('value'=>'Lilita One','label'=>'Lilita One');
		$krsgfont_array[] = array('value'=>'Limelight','label'=>' Limelight ');
		$krsgfont_array[] = array('value'=>'Linden Hill','label'=>'Linden Hill');
		$krsgfont_array[] = array('value'=>'Linden Hill:400,400italic','label'=>'Linden Hill:400,400italic');
		$krsgfont_array[] = array('value'=>'Lobster Two','label'=>'Lobster Two');
		$krsgfont_array[] = array('value'=>'Lobster Two:400,400italic,700,700italic','label'=>'Lobster Two (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Lobster','label'=>'Lobster');
		$krsgfont_array[] = array('value'=>'Londrina Outline','label'=>'Londrina Outline');
		$krsgfont_array[] = array('value'=>'Londrina Shadow','label'=>'Londrina Shadow');
		$krsgfont_array[] = array('value'=>'Londrina Sketch','label'=>'Londrina Sketch');
		$krsgfont_array[] = array('value'=>'Londrina Solid','label'=>'Londrina Solid');
		$krsgfont_array[] = array('value'=>'Lora','label'=>'Lora');
		$krsgfont_array[] = array('value'=>'Lora:400,700,400italic,700italic','label'=>'Lora (plus bold and italic)');
		$krsgfont_array[] = array('value'=>'Love Ya Like A Sister','label'=>'Love Ya Like A Sister');
		$krsgfont_array[] = array('value'=>'Lovers Quarrel','label'=>'Lovers Quarrel');
		$krsgfont_array[] = array('value'=>'Loved by the King','label'=>'Loved by the King');
		$krsgfont_array[] = array('value'=>'Luckiest Guy','label'=>'Luckiest Guy');
		$krsgfont_array[] = array('value'=>'Lusitana','label'=>'Lusitana');
		$krsgfont_array[] = array('value'=>'Lusitana:400,bold','label'=>'Lusitana (plus bold)');
		$krsgfont_array[] = array('value'=>'Lustria','label'=>'Lustria');
		$krsgfont_array[] = array('value'=>'Macondo Swash Caps','label'=>'Macondo Swash Caps');
		$krsgfont_array[] = array('value'=>'Macondo','label'=>'Macondo');
		$krsgfont_array[] = array('value'=>'Magra','label'=>'Magra');
		$krsgfont_array[] = array('value'=>'Magra:400,bold','label'=>'Magra (plus bold)');
		$krsgfont_array[] = array('value'=>'Maiden Orange','label'=>'Maiden Orange');
		$krsgfont_array[] = array('value'=>'Mako','label'=>'Mako');
		$krsgfont_array[] = array('value'=>'Marck Script','label'=>'Marck Script');
		$krsgfont_array[] = array('value'=>'Marko One','label'=>'Marko One');
		$krsgfont_array[] = array('value'=>'Marmelad','label'=>'Marmelad');
		$krsgfont_array[] = array('value'=>'Marvel','label'=>'Marvel ');
		$krsgfont_array[] = array('value'=>'Marvel:400,400italic,700,700italic','label'=>'Marvel (plus bold and italic) ');
		$krsgfont_array[] = array('value'=>'Mate SC','label'=>'Mate SC');
		$krsgfont_array[] = array('value'=>'Mate','label'=>'Mate');
		$krsgfont_array[] = array('value'=>'Mate:400,400italic','label'=>'Mate:400,400italic');
		$krsgfont_array[] = array('value'=>'Maven Pro','label'=>' Maven Pro');
		$krsgfont_array[] = array('value'=>'Maven Pro:500','label'=>' Maven Pro 500');
		$krsgfont_array[] = array('value'=>'Maven Pro:900','label'=>' Maven Pro 900');
		$krsgfont_array[] = array('value'=>'Maven Pro:bold','label'=>' Maven Pro 700');
		$krsgfont_array[] = array('value'=>'McLaren','label'=>'McLaren');
		$krsgfont_array[] = array('value'=>'Meddon','label'=>'Meddon');
		$krsgfont_array[] = array('value'=>'MedievalSharp','label'=>'MedievalSharp');
		$krsgfont_array[] = array('value'=>'Medula One','label'=>'Medula One');
		$krsgfont_array[] = array('value'=>'Megrim','label'=>'Megrim');
		$krsgfont_array[] = array('value'=>'Merienda One','label'=>'Merienda One');
		$krsgfont_array[] = array('value'=>'Merriweather','label'=>'Merriweather');
		$krsgfont_array[] = array('value'=>'Metamorphous','label'=>'Metamorphous');
		$krsgfont_array[] = array('value'=>'Metrophobic','label'=>'Metrophobic');
		$krsgfont_array[] = array('value'=>'Metal Mania','label'=>'Metal Mania');
		$krsgfont_array[] = array('value'=>'Michroma','label'=>'Michroma');
		$krsgfont_array[] = array('value'=>'Miltonian Tattoo','label'=>'Miltonian Tattoo');
		$krsgfont_array[] = array('value'=>'Miltonian','label'=>'Miltonian');
		$krsgfont_array[] = array('value'=>'Miniver','label'=>'Miniver');
		$krsgfont_array[] = array('value'=>'Miss Fajardose','label'=>'Miss Fajardose');
		$krsgfont_array[] = array('value'=>'Miss Saint Delafield','label'=>'Miss Saint Delafield');
		$krsgfont_array[] = array('value'=>'Modern Antiqua','label'=>'Modern Antiqua');
		$krsgfont_array[] = array('value'=>'Molengo','label'=>'Molengo');
		$krsgfont_array[] = array('value'=>'Monofett','label'=>'Monofett');
		$krsgfont_array[] = array('value'=>'Monoton','label'=>'Monoton ');
		$krsgfont_array[] = array('value'=>'Monsieur La Doulaise','label'=>'Monsieur La Doulaise');
		$krsgfont_array[] = array('value'=>'Montaga','label'=>'Montaga');
		$krsgfont_array[] = array('value'=>'Montez','label'=>'Montez ');
		$krsgfont_array[] = array('value'=>'Montserrat','label'=>'Montserrat');
		$krsgfont_array[] = array('value'=>'Mountains of Christmas','label'=>'Mountains of Christmas');
		$krsgfont_array[] = array('value'=>'Mr Bedford','label'=>'Mr Bedford');
		$krsgfont_array[] = array('value'=>'Mr Dafoe','label'=>'Mr Dafoe');
		$krsgfont_array[] = array('value'=>'Mr De Haviland','label'=>'Mr De Haviland');
		$krsgfont_array[] = array('value'=>'Mrs Saint Delafield','label'=>'Mrs Saint Delafield');
		$krsgfont_array[] = array('value'=>'Mrs Sheppards','label'=>'Mrs Sheppards');
		$krsgfont_array[] = array('value'=>'Muli','label'=>'Muli Regular');
		$krsgfont_array[] = array('value'=>'Muli:light','label'=>'Muli Light');
		$krsgfont_array[] = array('value'=>'Muli:light,lightitalic','label'=>'Muli Light (plus italic)');
		$krsgfont_array[] = array('value'=>'Muli:regular,regularitalic','label'=>'Muli Regular (plus italic)');
		$krsgfont_array[] = array('value'=>'Mystery Quest','label'=>'Mystery Quest');
		$krsgfont_array[] = array('value'=>'Neucha','label'=>'Neucha');
		$krsgfont_array[] = array('value'=>'Neuton','label'=>'Neuton');
		$krsgfont_array[] = array('value'=>'News Cycle','label'=>'News Cycle');
		$krsgfont_array[] = array('value'=>'Niconne','label'=>'Niconne');
		$krsgfont_array[] = array('value'=>'Nixie One','label'=>'Nixie One');
		$krsgfont_array[] = array('value'=>'Nobile','label'=>'Nobile');
		$krsgfont_array[] = array('value'=>'Nobile:regular,italic,bold,bolditalic','label'=>'Nobile (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Nokora','label'=>'Nokora');
		$krsgfont_array[] = array('value'=>'Nokora:400,700','label'=>'Nokora:400,700');
		$krsgfont_array[] = array('value'=>'Norican','label'=>'Norican');
		$krsgfont_array[] = array('value'=>'Nosifer','label'=>'Nosifer');
		$krsgfont_array[] = array('value'=>'Noticia Text','label'=>'Noticia Text');
		$krsgfont_array[] = array('value'=>'Noticia Text:400,400italic,700,700italic','label'=>'Noticia Text:400,400italic,700,700italic');
		$krsgfont_array[] = array('value'=>'Nova Cut','label'=>'Nova Cut');
		$krsgfont_array[] = array('value'=>'Nova Flat','label'=>'Nova Flat');
		$krsgfont_array[] = array('value'=>'Nova Mono','label'=>'Nova Mono');
		$krsgfont_array[] = array('value'=>'Nova Oval','label'=>'Nova Oval');
		$krsgfont_array[] = array('value'=>'Nova Round','label'=>'Nova Round');
		$krsgfont_array[] = array('value'=>'Nova Script','label'=>'Nova Script');
		$krsgfont_array[] = array('value'=>'Nova Slim','label'=>'Nova Slim');
		$krsgfont_array[] = array('value'=>'Nova Square','label'=>'Nova Square');
		$krsgfont_array[] = array('value'=>'Numans','label'=>'Numans ');
		$krsgfont_array[] = array('value'=>'Nunito','label'=>' Nunito Regular');
		$krsgfont_array[] = array('value'=>'Nunito:light','label'=>' Nunito Light');
		$krsgfont_array[] = array('value'=>'OFL Sorts Mill Goudy TT','label'=>'OFL Sorts Mill Goudy TT');
		$krsgfont_array[] = array('value'=>'OFL Sorts Mill Goudy TT:regular,italic','label'=>'OFL Sorts Mill Goudy TT (plus italic)');
		$krsgfont_array[] = array('value'=>'Old Standard TT','label'=>'Old Standard TT');
		$krsgfont_array[] = array('value'=>'Old Standard TT:regular,italic,bold','label'=>'Old Standard TT (plus italic and bold)');
		$krsgfont_array[] = array('value'=>'Oldenburg','label'=>'Oldenburg');
		$krsgfont_array[] = array('value'=>'Oleo Script','label'=>'Oleo Script');
		$krsgfont_array[] = array('value'=>'Oleo Script:400,700','label'=>'Oleo Script (plus bold)');
		$krsgfont_array[] = array('value'=>'Open Sans Condensed','label'=>'Open Sans Condensed');
		$krsgfont_array[] = array('value'=>'Open Sans Condensed:300,300italic,700','label'=>'Open Sans Condensed (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Open Sans Condensed:light,lightitalic','label'=>'Open Sans Condensed Light (plus italic)');
		$krsgfont_array[] = array('value'=>'Open Sans:600,600italic','label'=>'Open Sans 600');
		$krsgfont_array[] = array('value'=>'Open Sans:800,800italic','label'=>'Open Sans 800');
		$krsgfont_array[] = array('value'=>'Open Sans:bold,bolditalic','label'=>'Open Sans bold');
		$krsgfont_array[] = array('value'=>'Open Sans:light,lightitalic','label'=>'Open Sans light');
		$krsgfont_array[] = array('value'=>'Open Sans:light,lightitalic,regular,regularitalic,600,600italic,bold,bolditalic,800,800italic','label'=>'Open Sans (all weights)');
		$krsgfont_array[] = array('value'=>'Open Sans:regular,regularitalic','label'=>'Open Sans regular');
		$krsgfont_array[] = array('value'=>'Orbitron','label'=>'Orbitron Regular (400)');
		$krsgfont_array[] = array('value'=>'Orbitron:500','label'=>'Orbitron 500');
		$krsgfont_array[] = array('value'=>'Orbitron:900','label'=>'Orbitron 900');
		$krsgfont_array[] = array('value'=>'Orbitron:bold','label'=>'Orbitron Regular (700)');
		$krsgfont_array[] = array('value'=>'Oregano','label'=>'Oregano');
		$krsgfont_array[] = array('value'=>'Oregano:400,400italic','label'=>'Oregano (plus italic)');
		$krsgfont_array[] = array('value'=>'Original Surfer','label'=>'Original Surfer');
		$krsgfont_array[] = array('value'=>'Oswald','label'=>'Oswald');
		$krsgfont_array[] = array('value'=>'Over the Rainbow','label'=>'Over the Rainbow');
		$krsgfont_array[] = array('value'=>'Overlock SC','label'=>'Overlock SC');
		$krsgfont_array[] = array('value'=>'Overlock','label'=>'Overlock');
		$krsgfont_array[] = array('value'=>'Overlock:400,400italic,700,700italic,900,900italic','label'=>'Overlock:400,400italic,700,700italic,900,900italic');
		$krsgfont_array[] = array('value'=>'Ovo','label'=>'Ovo ');
		$krsgfont_array[] = array('value'=>'Oxygen','label'=>'Oxygen');
		$krsgfont_array[] = array('value'=>'PT Mono','label'=>'PT Mono');
		$krsgfont_array[] = array('value'=>'PT Sans Caption','label'=>'PT Sans Caption');
		$krsgfont_array[] = array('value'=>'PT Sans Caption:regular,bold','label'=>'PT Sans Caption (plus bold)');
		$krsgfont_array[] = array('value'=>'PT Sans Narrow','label'=>'PT Sans Narrow');
		$krsgfont_array[] = array('value'=>'PT Sans Narrow:regular,bold','label'=>'PT Sans Narrow (plus bold)');
		$krsgfont_array[] = array('value'=>'PT Sans','label'=>'PT Sans');
		$krsgfont_array[] = array('value'=>'PT Sans:regular,italic,bold,bolditalic','label'=>'PT Sans (plus itlic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'PT Serif Caption','label'=>'PT Serif Caption');
		$krsgfont_array[] = array('value'=>'PT Serif Caption:regular,italic','label'=>'PT Serif Caption (plus italic)');
		$krsgfont_array[] = array('value'=>'PT Serif','label'=>'PT Serif');
		$krsgfont_array[] = array('value'=>'PT Serif:regular,italic,bold,bolditalic','label'=>'PT Serif (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Pacifico','label'=>'Pacifico');
		$krsgfont_array[] = array('value'=>'Parisienne','label'=>'Parisienne');
		$krsgfont_array[] = array('value'=>'Passero One','label'=>'Passero One');
		$krsgfont_array[] = array('value'=>'Passion One','label'=>'Passion One');
		$krsgfont_array[] = array('value'=>'Passion One:400,700,900','label'=>'Passion One:400,700,900');
		$krsgfont_array[] = array('value'=>'Patrick Hand','label'=>'Patrick Hand');
		$krsgfont_array[] = array('value'=>'Patua One','label'=>'Patua One');
		$krsgfont_array[] = array('value'=>'Paytone One','label'=>'Paytone One');
		$krsgfont_array[] = array('value'=>'Peralta','label'=>'Peralta');
		$krsgfont_array[] = array('value'=>'Permanent Marker','label'=>'Permanent Marker');
		$krsgfont_array[] = array('value'=>'Petrona','label'=>'Petrona');
		$krsgfont_array[] = array('value'=>'Philosopher','label'=>'Philosopher');
		$krsgfont_array[] = array('value'=>'Piedra','label'=>'Piedra');
		$krsgfont_array[] = array('value'=>'Pinyon Script','label'=>'Pinyon Script');
		$krsgfont_array[] = array('value'=>'Plaster','label'=>'Plaster');
		$krsgfont_array[] = array('value'=>'Play','label'=>'Play');
		$krsgfont_array[] = array('value'=>'Play:regular,bold','label'=>'Play (plus bold)');
		$krsgfont_array[] = array('value'=>'Playball','label'=>'Playball');
		$krsgfont_array[] = array('value'=>'Playfair Display','label'=>' Playfair Display ');
		$krsgfont_array[] = array('value'=>'Podkova','label'=>' Podkova ');
		$krsgfont_array[] = array('value'=>'Poiret One','label'=>'Poiret One');
		$krsgfont_array[] = array('value'=>'Poller One','label'=>'Poller One');
		$krsgfont_array[] = array('value'=>'Poly','label'=>'Poly');
		$krsgfont_array[] = array('value'=>'Poly:400,400italic','label'=>'Poly:400,400italic');
		$krsgfont_array[] = array('value'=>'Pompiere','label'=>'Pompiere ');
		$krsgfont_array[] = array('value'=>'Pontano Sans','label'=>'Pontano Sans');
		$krsgfont_array[] = array('value'=>'Port Lligat Sans','label'=>'Port Lligat Sans');
		$krsgfont_array[] = array('value'=>'Port Lligat Slab','label'=>'Port Lligat Slab');
		$krsgfont_array[] = array('value'=>'Prata','label'=>'Prata');
		$krsgfont_array[] = array('value'=>'Press Start 2P','label'=>'Press Start 2P');
		$krsgfont_array[] = array('value'=>'Princess Sofia','label'=>'Princess Sofia');
		$krsgfont_array[] = array('value'=>'Prociono','label'=>'Prociono');
		$krsgfont_array[] = array('value'=>'Prosto One','label'=>'Prosto One');
		$krsgfont_array[] = array('value'=>'Puritan','label'=>'Puritan');
		$krsgfont_array[] = array('value'=>'Puritan:regular,italic,bold,bolditalic','label'=>'Puritan (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Quando','label'=>'Quando');
		$krsgfont_array[] = array('value'=>'Quantico','label'=>'Quantico');
		$krsgfont_array[] = array('value'=>'Quantico:400,400italic,700,700italic','label'=>'Quantico:400,400italic,700,700italic');
		$krsgfont_array[] = array('value'=>'Quattrocento Sans','label'=>'Quattrocento Sans');
		$krsgfont_array[] = array('value'=>'Quattrocento Sans:400,400italic,700,700italic','label'=>'Quattrocento Sans (plus bolds and italics)');
		$krsgfont_array[] = array('value'=>'Quattrocento','label'=>'Quattrocento');
		$krsgfont_array[] = array('value'=>'Quattrocento:400,700','label'=>'Quattrocento (plus bold)');
		$krsgfont_array[] = array('value'=>'Questrial','label'=>'Questrial ');
		$krsgfont_array[] = array('value'=>'Quicksand','label'=>'Quicksand');
		$krsgfont_array[] = array('value'=>'Quicksand:300,400,700','label'=>'Quicksand:300,400,700');
		$krsgfont_array[] = array('value'=>'Qwigley','label'=>'Qwigley');
		$krsgfont_array[] = array('value'=>'Racing Sans One','label'=>'Racing Sans One');
		$krsgfont_array[] = array('value'=>'Radley','label'=>'Radley');
		$krsgfont_array[] = array('value'=>'Raleway','label'=>'Raleway 400');
		$krsgfont_array[] = array('value'=>'Raleway:400,300,600,500,200,100,700,800,900','label'=>'Raleway all weight');
		$krsgfont_array[] = array('value'=>'Rammetto One','label'=>'Rammetto One');
		$krsgfont_array[] = array('value'=>'Rancho','label'=>'Rancho');
		$krsgfont_array[] = array('value'=>'Rationale','label'=>'Rationale ');
		$krsgfont_array[] = array('value'=>'Redressed','label'=>'Redressed');
		$krsgfont_array[] = array('value'=>'Reenie Beanie','label'=>'Reenie Beanie');
		$krsgfont_array[] = array('value'=>'Revalia','label'=>'Revalia');
		$krsgfont_array[] = array('value'=>'Ribeye Marrow','label'=>'Ribeye Marrow');
		$krsgfont_array[] = array('value'=>'Ribeye','label'=>'Ribeye');
		$krsgfont_array[] = array('value'=>'Righteous','label'=>'Righteous');
		$krsgfont_array[] = array('value'=>'Roboto','label'=>'Roboto');
		$krsgfont_array[] = array('value'=>'Roboto:300','label'=>'Roboto:300');
		$krsgfont_array[] = array('value'=>'Roboto:700','label'=>'Roboto:700');
		$krsgfont_array[] = array('value'=>'Rochester','label'=>'Rochester');
		$krsgfont_array[] = array('value'=>'Rock Salt','label'=>'Rock Salt');
		$krsgfont_array[] = array('value'=>'Rokkitt','label'=>'Rokkitt');
		$krsgfont_array[] = array('value'=>'Romanesco','label'=>'Romanesco');
		$krsgfont_array[] = array('value'=>'Ropa Sans','label'=>'Ropa Sans');
		$krsgfont_array[] = array('value'=>'Ropa Sans:400,400italic','label'=>'Ropa Sans (plus italics)');
		$krsgfont_array[] = array('value'=>'Rosario','label'=>'Rosario ');
		$krsgfont_array[] = array('value'=>'Rosarivo:400,400italic','label'=>'Rosarivo (plus italic)');		$krsgfont_array[] = array('value'=>'Rouge Script','label'=>'Rouge Script');
		$krsgfont_array[] = array('value'=>'Ruda','label'=>'Ruda');
		$krsgfont_array[] = array('value'=>'Ruda:400,bold,900','label'=>'Ruda (plus all bold and 900)');
		$krsgfont_array[] = array('value'=>'Ruge Boogie','label'=>'Ruge Boogie');
		$krsgfont_array[] = array('value'=>'Ruluko','label'=>'Ruluko');
		$krsgfont_array[] = array('value'=>'Ruslan Display','label'=>'Ruslan Display');
		$krsgfont_array[] = array('value'=>'Russo One','label'=>'Russo One');
		$krsgfont_array[] = array('value'=>'Ruthie','label'=>'Ruthie');
		$krsgfont_array[] = array('value'=>'Sail','label'=>'Sail');
		$krsgfont_array[] = array('value'=>'Salsa','label'=>'Salsa');
		$krsgfont_array[] = array('value'=>'Sancreek','label'=>'Sancreek');
		$krsgfont_array[] = array('value'=>'Sansita One','label'=>'Sansita One');
		$krsgfont_array[] = array('value'=>'Sarina','label'=>'Sarina');
		$krsgfont_array[] = array('value'=>'Satisfy','label'=>'Satisfy');
		$krsgfont_array[] = array('value'=>'Schoolbell','label'=>'Schoolbell');
		$krsgfont_array[] = array('value'=>'Seaweed Script','label'=>'Seaweed Script');
		$krsgfont_array[] = array('value'=>'Sevillana','label'=>'Sevillana');
		$krsgfont_array[] = array('value'=>'Shadows Into Light Two','label'=>'Shadows Into Light Two');
		$krsgfont_array[] = array('value'=>'Shadows Into Light','label'=>'Shadows Into Light');
		$krsgfont_array[] = array('value'=>'Shanti','label'=>'Shanti');
		$krsgfont_array[] = array('value'=>'Share','label'=>'Share');
		$krsgfont_array[] = array('value'=>'Share:400,400italic,700,700italic','label'=>'Share (plus all weights and italics)');
		$krsgfont_array[] = array('value'=>'Shojumaru','label'=>'Shojumaru');
		$krsgfont_array[] = array('value'=>'Short Stack','label'=>'Short Stack ');
		$krsgfont_array[] = array('value'=>'Sigmar One','label'=>'Sigmar One');
		$krsgfont_array[] = array('value'=>'Signika Negative','label'=>'Signika Negative');
		$krsgfont_array[] = array('value'=>'Signika Negative:300,400,600,700','label'=>'Signika Negative:300,400,600,700');
		$krsgfont_array[] = array('value'=>'Signika','label'=>'Signika');
		$krsgfont_array[] = array('value'=>'Signika:300,400,600,700','label'=>'Signika:300,400,600,700');
		$krsgfont_array[] = array('value'=>'Simonetta','label'=>'Simonetta');
		$krsgfont_array[] = array('value'=>'Simonetta:400,400italic','label'=>'Simonetta (plus italic)');
		$krsgfont_array[] = array('value'=>'Sirin Stencil','label'=>'Sirin Stencil');
		$krsgfont_array[] = array('value'=>'Six Caps','label'=>'Six Caps');
		$krsgfont_array[] = array('value'=>'Slackey','label'=>'Slackey');
		$krsgfont_array[] = array('value'=>'Smokum','label'=>'Smokum ');
		$krsgfont_array[] = array('value'=>'Smythe','label'=>'Smythe');
		$krsgfont_array[] = array('value'=>'Sniglet:800','label'=>'Sniglet');
		$krsgfont_array[] = array('value'=>'Snippet','label'=>'Snippet ');
		$krsgfont_array[] = array('value'=>'Sofia','label'=>'Sofia');
		$krsgfont_array[] = array('value'=>'Sonsie One','label'=>'Sonsie One');
		$krsgfont_array[] = array('value'=>'Sorts Mill Goudy','label'=>'Sorts Mill Goudy');
		$krsgfont_array[] = array('value'=>'Sorts Mill Goudy:400,400italic','label'=>'Sorts Mill Goudy (plus italic)');
		$krsgfont_array[] = array('value'=>'Source Sans Pro','label'=>'Source Sans Pro');
		$krsgfont_array[] = array('value'=>'Source Sans Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic','label'=>'Source Sans Pro (all weights plus italics)');
		$krsgfont_array[] = array('value'=>'Special Elite','label'=>'Special Elite');
		$krsgfont_array[] = array('value'=>'Spicy Rice','label'=>'Spicy Rice');
		$krsgfont_array[] = array('value'=>'Spinnaker','label'=>'Spinnaker');
		$krsgfont_array[] = array('value'=>'Spirax','label'=>'Spirax');
		$krsgfont_array[] = array('value'=>'Squada One','label'=>'Squada One');
		$krsgfont_array[] = array('value'=>'Stardos Stencil','label'=>'Stardos Stencil');
		$krsgfont_array[] = array('value'=>'Stardos Stencil:400,700','label'=>'Stardos Stencil (plus bold)');
		$krsgfont_array[] = array('value'=>'Stint Ultra Condensed','label'=>'Stint Ultra Condensed');
		$krsgfont_array[] = array('value'=>'Stint Ultra Expanded','label'=>'Stint Ultra Expanded');
		$krsgfont_array[] = array('value'=>'Stoke','label'=>'Stoke');
		$krsgfont_array[] = array('value'=>'Stoke:400,300','label'=>'Stoke (plus 400)');
		$krsgfont_array[] = array('value'=>'Sue Ellen Francisco','label'=>'Sue Ellen Francisco');
		$krsgfont_array[] = array('value'=>'Sunshiney','label'=>'Sunshiney');
		$krsgfont_array[] = array('value'=>'Supermercado One','label'=>'Supermercado One');
		$krsgfont_array[] = array('value'=>'Swanky and Moo Moo','label'=>'Swanky and Moo Moo');
		$krsgfont_array[] = array('value'=>'Syncopate','label'=>'Syncopate');
		$krsgfont_array[] = array('value'=>'Tangerine','label'=>'Tangerine');
		$krsgfont_array[] = array('value'=>'Telex','label'=>'Telex');
		$krsgfont_array[] = array('value'=>'Tenor Sans','label'=>' Tenor Sans ');
		$krsgfont_array[] = array('value'=>'Terminal Dosis Light','label'=>'Terminal Dosis Light');
		$krsgfont_array[] = array('value'=>'Terminal Dosis','label'=>'Terminal Dosis Regular');
		$krsgfont_array[] = array('value'=>'Terminal Dosis:200','label'=>'Terminal Dosis 200');
		$krsgfont_array[] = array('value'=>'Terminal Dosis:300','label'=>'Terminal Dosis 300');
		$krsgfont_array[] = array('value'=>'Terminal Dosis:500','label'=>'Terminal Dosis 500');
		$krsgfont_array[] = array('value'=>'Terminal Dosis:600','label'=>'Terminal Dosis 600');
		$krsgfont_array[] = array('value'=>'Terminal Dosis:700','label'=>'Terminal Dosis 700');
		$krsgfont_array[] = array('value'=>'Terminal Dosis:800','label'=>'Terminal Dosis 800');
		$krsgfont_array[] = array('value'=>'The Girl Next Door','label'=>'The Girl Next Door');
		$krsgfont_array[] = array('value'=>'Tinos','label'=>'Tinos');
		$krsgfont_array[] = array('value'=>'Tinos:regular,italic,bold,bolditalic','label'=>'Tinos (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Titan One','label'=>'Titan One');
		$krsgfont_array[] = array('value'=>'Trade Winds','label'=>'Trade Winds');
		$krsgfont_array[] = array('value'=>'Trocchi','label'=>'Trocchi');
		$krsgfont_array[] = array('value'=>'Trochut','label'=>'Trochut');
		$krsgfont_array[] = array('value'=>'Trochut:400,italic,bold','label'=>'Trochut (plus bold and italic)');
		$krsgfont_array[] = array('value'=>'Trykker','label'=>'Trykker');
		$krsgfont_array[] = array('value'=>'Tulpen One','label'=>'Tulpen One ');
		$krsgfont_array[] = array('value'=>'Ubuntu Condensed','label'=>'Ubuntu Condensed');
		$krsgfont_array[] = array('value'=>'Ubuntu Mono','label'=>'Ubuntu Mono');
		$krsgfont_array[] = array('value'=>'Ubuntu Mono:regular,italic,bold,bolditalic','label'=>'Ubuntu Mono:regular,italic,bold,bolditalic');
		$krsgfont_array[] = array('value'=>'Ubuntu','label'=>'Ubuntu');
		$krsgfont_array[] = array('value'=>'Ubuntu:regular,italic,bold,bolditalic','label'=>'Ubuntu (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Ultra','label'=>'Ultra');
		$krsgfont_array[] = array('value'=>'Uncial Antiqua','label'=>'Uncial Antiqua');
		$krsgfont_array[] = array('value'=>'UnifrakturCook:bold','label'=>'UnifrakturCook');
		$krsgfont_array[] = array('value'=>'UnifrakturMaguntia','label'=>'UnifrakturMaguntia');
		$krsgfont_array[] = array('value'=>'Unkempt','label'=>'Unkempt');
		$krsgfont_array[] = array('value'=>'Unlock','label'=>'Unlock');
		$krsgfont_array[] = array('value'=>'Unna','label'=>'Unna ');
		$krsgfont_array[] = array('value'=>'VT323','label'=>'VT323');
		$krsgfont_array[] = array('value'=>'Varela Round','label'=>'Varela Round');
		$krsgfont_array[] = array('value'=>'Varela','label'=>'Varela');
		$krsgfont_array[] = array('value'=>'Vast Shadow','label'=>'Vast Shadow');
		$krsgfont_array[] = array('value'=>'Vibur','label'=>'Vibur');
		$krsgfont_array[] = array('value'=>'Vidaloka','label'=>'Vidaloka ');
		$krsgfont_array[] = array('value'=>'Viga','label'=>'Viga');
		$krsgfont_array[] = array('value'=>'Voces','label'=>'Voces');
		$krsgfont_array[] = array('value'=>'Volkhov','label'=>'Volkhov ');
		$krsgfont_array[] = array('value'=>'Volkhov:400,400italic,700,700italic','label'=>'Volkhov (plus bold and italic) ');
		$krsgfont_array[] = array('value'=>'Vollkorn','label'=>'Vollkorn');
		$krsgfont_array[] = array('value'=>'Vollkorn:regular,italic,bold,bolditalic','label'=>'Vollkorn (plus italic, bold, and bold italic)');
		$krsgfont_array[] = array('value'=>'Voltaire','label'=>'Voltaire ');
		$krsgfont_array[] = array('value'=>'Waiting for the Sunrise','label'=>'Waiting for the Sunrise');
		$krsgfont_array[] = array('value'=>'Wallpoet','label'=>'Wallpoet');
		$krsgfont_array[] = array('value'=>'Walter Turncoat','label'=>'Walter Turncoat');
		$krsgfont_array[] = array('value'=>'Wellfleet','label'=>'Wellfleet');
		$krsgfont_array[] = array('value'=>'Wire One','label'=>'Wire One');
		$krsgfont_array[] = array('value'=>'Yanone Kaffeesatz','label'=>'Yanone Kaffeesatz');
		$krsgfont_array[] = array('value'=>'Yanone Kaffeesatz:300','label'=>'Yanone Kaffeesatz:300');
		$krsgfont_array[] = array('value'=>'Yanone Kaffeesatz:400','label'=>'Yanone Kaffeesatz:400');
		$krsgfont_array[] = array('value'=>'Yanone Kaffeesatz:700','label'=>'Yanone Kaffeesatz:700');
		$krsgfont_array[] = array('value'=>'Yellowtail','label'=>'Yellowtail ');
		$krsgfont_array[] = array('value'=>'Yeseva One','label'=>'Yeseva One');
		$krsgfont_array[] = array('value'=>'Yesteryear','label'=>'Yesteryear');
		$krsgfont_array[] = array('value'=>'Zeyada','label'=>'Zeyada');
	return $krsgfont_array;
}
?>